### ISSUE TITLE
SECRET_KEY_BASE -> RAILS_SECRET_KEY_BASE

### ISSUE THREAD

**Issue by koffeinfrei** [panter/panter-rails-deploy#8]
The rails default for the secret env var is `SECRET_KEY_BASE`. Is there a reason for having `RAILS_SECRET_KEY_BASE` in the readme?

**Comment by toupeira** [comment]
This wasn't deliberate, I think I just put this into the README because we were using this in the project I happened to look at while writing it ;-)

That said, I think the `RAILS_` prefix actually makes sense to indicate its scope, depending on the project there might be another library or even app that needs its own secret key. If you agree, I'd be happy to add a comment to the README to that effect.

**Comment by koffeinfrei** [comment]
Ok, agreed.
